core/urls.py


from django.urls import path
from . import views

urlpatterns=[
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact')
]

django-ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index, contact
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', index, name='index'),
    path('', include('core.urls')),
    # path('contact/', contact, name='contact')
    path('item/', include('item.urls')),

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views

app_name='item' #this is used to identify the app in the template(html files for href links)
urlpatterns=[
    path('<int:pk>/', views.detail, name='detail') #pk is the primary key of the item expected to be passed in the detail view
]

core/models.py
from django.db import models

# Create your models here.

item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=255)
    class Meta: #This updates the table name displayed in django administration page
        ordering =('name',) #order the fields by name,  comma is needed at the end because it is an iterable
        verbose_name_plural='Categories'
    def __str__(self):
        return self.name #display category name rather than object
    
class Item(models.Model):
    category=models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    description=models.TextField(blank=True, null=True)
    price=models.FloatField()
    image=models.ImageField(upload_to='item_images', blank=True, null=True) #upload_to is used to specify the folder where the image will be uploaded to
    is_sold=models.BooleanField(default=False)
    #link createdby to user table, related_name is used to get all the items created by the tied user, on_delete is used to delete all the items created by a user when the user is deleted
    created_by=models.ForeignKey(User, related_name='items', on_delete=models.CASCADE) 
    created_at=models.DateTimeField(auto_now_add=True) #auto_now_add is used to add the current date and time when the item is created
    def __str__(self):
        return self.name

core/views.py
from django.shortcuts import render

# Create your views here.
from item.models import Category, Item

def index(request):
    items=Item.objects.filter(is_sold=False)[0:6]
    categories=Category.objects.all()
    return render(request, 'core/index.html', {
        'items':items,
        'categories':categories
    })

def contact(request):
    return render(request, 'core/contact.html')

item/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item

# Create your views here.
def detail(request, pk):
    item=get_object_or_404(Item, pk=pk)# if item does not exist, return 404 error
    related_items= Item.objects.filter(category=item.category, is_sold=False).exclude(pk=item.pk)[:3]# get 3 related items
    return render(request, 'item/detail.html', {'item':item,
                                                'related_items':related_items
                                                })# render the item detail page

core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <mata name="viewport" content="width=device-width, initial-scale=1.0">
            <!-- Tailwind as a CDN -->
        <script src="https://cdn.tailwindcss.com"></script>
        <title> {% block title%}{% endblock %} | Puddle</title>
    </head>
    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Puddle</a>
            <div class="space-x-6">
                <a href="#" class="text-lg font-semibold hover:text-gray-500">New item</a>
                <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>
            
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            </div>

        </nav>
        <div class="px-6 py-4">
            {% block content %}{% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <p class="text-lg text-gray-500">Lorep ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, voluptatibus.</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</li>
                    <li><a href="{% url 'contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</li>
                </ul>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<h1>The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div class ="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest items</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
        <div>
        <a href="{% url 'item:detail' item.id %}">
            <div>
                {% if item.image %}
                <img src="{{item.image.url}}" class="rounded-t-xl">
                {% else %}
                <img src="https://via.placeholder.com/300" class="rounded-t-xl">
                {% endif %}
            </div>
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="text-2xl">{{ item.name }}</h2>
                <p class="text-gray-500">Price: {{ item.price }}</p>
            </div>
        </a>
        </div>
        {% endfor %}
    </div>
</div>
<div class ="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>
    <div class="grid grid-cols-3 gap-3">
    {% for category in categories %}
    <div>
        <a href="#">
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="text-2xl">{{ category.name }}</h2>
                <p class="text-gray-500">{{category.items.count}}</p>
            </div>
        </a>
        </div>
    {%endfor%}
    </div>  
</div>
{% endblock %}

item/templates/item/detail.html
{% extends 'core/base.html' %}

{%block title %}{{ item.name}}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        {% if item.image %}
        <img src="{{item.image.url}}" class="rounded-xl">
        {% else %}
        <img src="https://via.placeholder.com/300" class="rounded-xl">
        {% endif %}
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
        <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by.username }}</p>

        {% if item.description %}
        <p class="text-gray-700">
            <strong class="text-gray-500" >Description: </strong><br>
            {{ item.description }}
        </p>
        {% endif %}
        <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
    </div>
</div>

<div class ="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related items</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
        <div>
        <a href="{% url 'item:detail' item.id %}">
            <div>
                {% if item.image %}
                <img src="{{item.image.url}}" class="rounded-t-xl">
                {% else %}
                <img src="https://via.placeholder.com/300" class="rounded-t-xl">
                {% endif %}
            </div>
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="text-2xl">{{ item.name }}</h2>
                <p class="text-gray-500">Price: {{ item.price }}</p>
            </div>
        </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}